version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd LoanManagementMicroservice
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/loansapp .
      - docker tag service/loansapp $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/loan-service:loansapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/loan-service:loansapp
      - printf '[{"name":"loansapp-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/loan-service:loansapp>taskdefinition.json
artifacts:
   files:
   - LoanManagementMicroservice/taskdefinition.json