version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd PortalLoan
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/portalapp .
      - docker tag service/portalapp $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portal-service:portalapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portal-service:portalapp
      - printf '[{"name":"portalapp-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portal-service:portalapp>taskdefinition.json
artifacts:
   files:
   - PortalLoan/taskdefinition.json