version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd CollateralsManagementMicroservice
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/collateralsapp .
      - docker tag service/collateralsapp $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/collateral-service:collateralsapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/collateral-service:collateralsapp
      - printf '[{"name":"collateralsapp-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/collateral-service:collateralsapp>taskdefinition.json
artifacts:
   files:
   - CollateralsManagementMicroservice/taskdefinition.json